{% set name = "jemoji" %}
{% set version = "0.13.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 5d4c3e8e2cbbb2b73997c31294f6f70c94e4d4fade039373e86835bcf5529e7c

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-gemoji >=3.0,<4
    - rb-html-pipeline >=2.2,<3
    - rb-jekyll >=3.0,<5

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: GitHub-flavored emoji plugin for Jekyll

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/jekyll/{{ name }}

extra:
  recipe-maintainers:
    - sodre
