{% set name = "jemoji" %}
{% set version = "0.12.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: e9b2b129b393b190cf78d51bc4e178e2bf30aa8e9f1a587b366e978fb35d5d27

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-gemoji >=3.0,<4
    - rb-html-pipeline >=2.2,<3
    - rb-jekyll >=3.0,<5

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: GitHub-flavored emoji plugin for Jekyll

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/jekyll/{{ name }}

extra:
  recipe-maintainers:
    - sodre
