travis:
  secure:
    BINSTAR_TOKEN: aKJBbKKSh4VCaBkwRfd6VP0FbnVkR95yluMrl19g950tfOXLqC4fPOonjfrbo2PhDVz/UmjecOt6vHH9LTNsfYeca1nrIJsZaqZtzVe2GdQgNLsPiF6lzK4pAZ2AO2S4Iqbi2mTHMuQSyXCjBR9PSB1cYLZXF2qwKkDLGtAtuyBYplpwE1SHhg/WbRA1ftYdKzMXo7bAuV2DrC8d2XK0gOSdKd16qobvcTH6bJfJN/Aq+Hd/X/JBA6sVOI5JuLWoxAqdJPsE9vHqI7HJsbAgyZOWg/4a2/HKczYpHOeKKap+FNp/NMUEKr/lo0sVNitx76r3Lt0gp4FKBMsIe0HVsc1CULRcceyuna5uvj6Qxp9WvhaomqDce/kMJ4zCUvcBUkTN5knT+3T2ohpD3UqtHpjjtNGMSvzFdlDo6cXMXgD+QUXYoL/tXdeA3Xgu5Cq6oO/azLzybMEtMM2uLIEGK/9Sfbr1PtIGR9AxqC9SPnhOEGBZ1ezuCwUNozHmYJsJOK26BalhMm0brAZEqyu1L2mKVv6nPvfFk6DMGRPWCFkW4L/IlzYSQSAA+fMkcLYizeNhxkJehrdSvi4W0gbUSX5ONIzgiSP0z12IIGM+M9TV/qx9VgPU5ux/cekXq4LJ+ZD0ZA9I8fYbn+50ndvooXacVdIhJZbUko0orUr928k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
